[package]
name = "kitchensinkrust"
version = "0.1.0"
edition = "2021"
default-run = "main1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.17"
typenum = "1.17.0"

